### ISSUE TITLE
About the problem of self generating datasets

### ISSUE THREAD

**Issue by zxpekko** [MaxiBoether/mis-benchmark-framework#4] opened 2022-10-19 03:09 UTC
Hello, last time I used the dataset provided by the code, the effect was good. But I want to construct a dataset of SAT problem graph by myself, using the intel_ treesearch method training requires the use of a dataset composed of mat files, while I only downloaded cnf files from the official website of SAT instances. How do you convert cnf files into mat files or how are those mat files generated?

**Comment by MaxiBoether** [comment] 2022-10-26 18:50
Hi,

I am not quite sure yet what you want to achieve: You want to use the official SATLIB data set, or do you want to use custom SAT instances in the solver? In both cases, you will need the cnf files. Then, you can use the `gendata` functionality of the main script to generate graphs. It should be something like `python main.py gendata sat path/to/cnf/files path/to/output`. Does that help you?

**Comment by MaxiBoether** [comment] 2022-12-12 13:51
I will close this because I am not sure what the issue is and the author has not responded. Feel free to comment again.

**Closed as completed by MaxiBoether** 2022-12-12 13:51 UTC
